name: Main

on: [pull_request, push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install deps
        run: yarn
      - name: Check types
        run: yarn check-types
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
